
###
POST https://adminc.pro-matters.com/api/V2/Authentication
Content-Type: application/json

{
    "UserName": "",
    "Password": "",
    "SubscriberId": "7b4c94dc-b43e-4a2d-833a-58a6456148a2",
    "ConsumerID": "1807430a-9b0c-4a10-8ad8-341616d058fa"
}


###
GET https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/ HTTP/1.1
Authorization: token 



###
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/c40f0000-569f-0050-302a-08dd05d3444c HTTP/1.1
Authorization: token 
